/**
 * Client type for authentication.
 * @public
 */
export type ClientType = 'eoa' | 'base';

/**
 * Trading mode for user interface.
 * @public
 */
export type TradingMode = 'SIMPLE' | 'ADVANCED';

/**
 * Authentication headers required for login.
 * @public
 */
export interface SignatureHeaders {
  /**
   * The Ethereum address of the user
   */
  'x-account': string;

  /**
   * The signing message in hex format
   */
  'x-signing-message': string;

  /**
   * The signature generated by signing the message with the user's wallet
   */
  'x-signature': string;
}

/**
 * User rank information.
 * @public
 */
export interface UserRank {
  /**
   * Rank ID
   */
  id: number;

  /**
   * Rank name
   */
  name: string;

  /**
   * Fee rate in basis points
   */
  feeRateBps: number;
}

/**
 * Referral data for a user.
 * @public
 */
export interface ReferralData {
  /**
   * Referral creation timestamp
   */
  createdAt: string;

  /**
   * Referral ID
   */
  id: number;

  /**
   * Referred user's profile ID
   */
  referredProfileId: number;

  /**
   * Profile picture URL
   */
  pfpUrl: string | null;

  /**
   * Display name
   */
  displayName: string;
}

/**
 * User profile information returned after authentication (1:1 with API response).
 * @public
 */
export interface UserProfile {
  // Core fields
  /**
   * User ID (used as ownerId for orders)
   */
  id: number;

  /**
   * User's Ethereum address (EOA)
   */
  account: string;

  /**
   * Client type used for authentication
   */
  client: ClientType;

  /**
   * User rank information containing feeRateBps
   */
  rank?: UserRank;

  /**
   * Account creation timestamp
   */
  createdAt?: string;

  // Profile information
  /**
   * Username
   */
  username?: string;

  /**
   * Display name for the user
   */
  displayName?: string;

  /**
   * Profile picture URL
   */
  pfpUrl?: string;

  /**
   * User bio
   */
  bio?: string;

  /**
   * Social media URL
   */
  socialUrl?: string;

  /**
   * Trade wallet option
   */
  tradeWalletOption?: string;

  /**
   * Embedded account address
   */
  embeddedAccount?: string;

  // Points and gamification
  /**
   * Total points
   */
  points?: number;

  /**
   * Accumulative points
   */
  accumulativePoints?: number;

  /**
   * Whether enrolled in points program
   */
  enrolledInPointsProgram?: boolean;

  /**
   * Position on leaderboard
   */
  leaderboardPosition?: number;

  /**
   * Whether user is in top 100
   */
  isTop100?: boolean;

  /**
   * Whether user is a captain
   */
  isCaptain?: boolean;

  // Referral data
  /**
   * List of referral information
   */
  referralData?: ReferralData[];

  /**
   * Count of referred users
   */
  referredUsersCount?: number;
}

/**
 * Mode information from authentication response.
 * @public
 */
export interface ModeInfo {
  /**
   * Trading interface mode
   */
  mode: TradingMode;

  /**
   * Whether the user is new to the platform
   */
  isUserNew: boolean;
}

/**
 * User data for order operations.
 *
 * @remarks
 * Contains user-specific information needed for creating orders.
 * Typically extracted from authentication result.
 *
 * @public
 */
export interface UserData {
  /**
   * User ID (owner ID) from the API
   */
  userId: number;

  /**
   * Fee rate in basis points for this user
   * Common values: 100 (1%), 200 (2%), 300 (3%)
   */
  feeRateBps: number;
}

/**
 * Complete authentication result including session and profile.
 * @public
 */
export interface AuthResult {
  /**
   * Session cookie value (JWT token)
   */
  sessionCookie: string;

  /**
   * User profile information
   */
  profile: UserProfile;
}

/**
 * Options for login authentication.
 * @public
 */
export interface LoginOptions {
  /**
   * Client type to use for authentication
   * @defaultValue 'eoa'
   */
  client?: ClientType;
}
