/**
 * Client type for authentication.
 * @public
 */
export type ClientType = 'eoa' | 'base' | 'etherspot';

/**
 * Trading mode for user interface.
 * @public
 */
export type TradingMode = 'SIMPLE' | 'ADVANCED';

/**
 * Authentication headers required for login.
 * @public
 */
export interface SignatureHeaders {
  /**
   * The Ethereum address of the user
   */
  'x-account': string;

  /**
   * The signing message in hex format
   */
  'x-signing-message': string;

  /**
   * The signature generated by signing the message with the user's wallet
   */
  'x-signature': string;
}

/**
 * User profile information returned after authentication.
 * @public
 */
export interface UserProfile {
  /**
   * User's Ethereum address (EOA)
   */
  account: string;

  /**
   * Display name for the user
   */
  displayName: string;

  /**
   * Smart wallet address (optional, required for ETHERSPOT client)
   */
  smartWallet?: string;

  /**
   * Client type used for authentication
   */
  client: ClientType;
}

/**
 * Mode information from authentication response.
 * @public
 */
export interface ModeInfo {
  /**
   * Trading interface mode
   */
  mode: TradingMode;

  /**
   * Whether the user is new to the platform
   */
  isUserNew: boolean;
}

/**
 * User data for order operations.
 *
 * @remarks
 * Contains user-specific information needed for creating orders.
 * Typically extracted from authentication result.
 *
 * @public
 */
export interface UserData {
  /**
   * User ID (owner ID) from the API
   */
  userId: number;

  /**
   * Fee rate in basis points for this user
   * Common values: 100 (1%), 200 (2%), 300 (3%)
   */
  feeRateBps: number;
}

/**
 * Complete authentication result including session and profile.
 * @public
 */
export interface AuthResult {
  /**
   * Session cookie value (JWT token)
   */
  sessionCookie: string;

  /**
   * User profile information
   */
  profile: UserProfile;
}

/**
 * Options for login authentication.
 * @public
 */
export interface LoginOptions {
  /**
   * Client type to use for authentication
   * @defaultValue 'eoa'
   */
  client?: ClientType;

  /**
   * Smart wallet address (required when client is 'etherspot')
   */
  smartWallet?: string;
}
